### PR TITLE
Fixing MacOS build errors

### PR DESCRIPTION
**Pull request by Gothbr4dn**
I fixed all of the errors for Mac

### CODE REVIEW

**Comment by polybiusproxy** [comment]
why is people making pull requests

**Comment by Gothbr4dn** [comment]
I fixed macOS compile error's

**Comment by EyeDaleHim** [comment]
Not sure if I want this accepted or not, since it also includes a shader thing, which is not the purpose of this PR.

**Comment by Gothbr4dn** [comment]
> Not sure if I want this accepted or not, since it also includes a shader thing, which is not the purpose of this PR.

thanks for reminding me to delete that

**Comment by polybiusproxy** [comment]
Anyways, I won't merge anything, **even if I want to**.
The current branch is protected, therefore I cannot commit anymore to it.

**Pull request closed without merging**
