### PR TITLE
Fixing MacOS build errors

### PR DESCRIPTION
**Pull request by Gothbr4dn**

### CODE REVIEW

**Comment by Gothbr4dn** [comment]
I made a branch for it I have to change it

**Comment by REALHaydenGaming** [comment]
My man, we could honestly care less. Plus MacOS people barely do/even make fnf mods. LMAFO

**Comment by REALHaydenGaming** [comment]
So this is a useless PR

**Comment by Gothbr4dn** [comment]
> My man, we could honestly care less. Plus MacOS people barely do/even make fnf mods. LMAFO

I am working on 4 mods right now for other people and my main OS is Mac

**Pull request closed without merging**
