### PR TITLE
fixed stuff for macos

### PR DESCRIPTION
**Pull request by JonnycatMeow**
@brightfyregit please merge i have i tested this

### CODE REVIEW

**Review by REALHaydenGaming — CHANGES_REQUESTED** [review]
I've seen better.

**Comment by JonnycatMeow** [comment]
wow

**Review by TheRealJake12 — APPROVED** [review]

**Comment by jasondingus** [comment]
yall know that proxy dont accept PR right?

**Review by polybiusproxy — APPROVED** [review]

**Comment by polybiusproxy** [comment]
Nice, but I can't accept pull requests, sorry

**Pull request closed without merging**
